### PR TITLE
Pass classname and id to root component

### LINKED ISSUE #30: Pass classname and id to notification component
This is useful when you want to override the styling of the notification containers using something like `styled-components` without relying on `.css` files. For example, if you pass the className, you can do the following:

``` javascript
const StyledContainer = styled(ReactNotification)`
	.react-notification-root .notification-item {
		box-shadow: none;
	}
`
```
but `styled-components` rely on the component passing the classname to the underlying tag.

### PR DESCRIPTION
**Pull request by sradevski**
Fixes #30

### CODE REVIEW

**Comment by teodosii** [comment]
Why bother with `otherProps` when you could destructure `this.props` inside the two renderers? I will merge the PR only after this change.

**Comment by teodosii** [comment]
Also we need to update `readme` to let people know about the change, otherwise it's kinda pointless

**Comment by sradevski** [comment]
@teodosii addressed the comments, have another look at it

**Comment by teodosii** [comment]
Looks good, will merge it

**Pull request merged**
