### PR TITLE
Replace existing notifications w/ same id

### LINKED ISSUE #90: Replace content if a notification with the same ID exists
This is related to https://github.com/teodosii/react-notifications-component/issues/40, but I'd like to restart the discussion, cause simply removing the notification doesn't quite work (without doing some timing calculations).

The reason removing the old notification doesn't work is, the actual DOM node isn't removed until the animation finishes, so you would have to remove the old notification, wait for the animation to finish, and only then add a new notification. Since there is no method exposed to check if a notification exists or not (you could do a direct DOM access on the ID, but it's not a very clean solution), you'd have to wait for the animation duration regardless of whether a notification with the passed ID exists or not. Also, having the content replaced is cleaner UX-wise, cause you keep the context inside the same notification container (so you don't get the exit and enter animations, maybe have some animation inside the notification container itself).

What I suggest doing is, either implicitly replace the content when you do `addNotification` with an ID that already exists, or add a new `replaceNotification(id, options)` method. I personally prefer the former one, but it doesn't matter as much for me.

### PR DESCRIPTION
**Pull request by kkkrist**
… rather than adding a copy

Resolves #90

### CODE REVIEW

**Comment by teodosii** [comment]
Does this take height adjustment into consideration? If the initial notification was `30px` and the new content spans to `90px` then the notification display is messed up.

**Comment by kkkrist** [comment]
> Does this take height adjustment into consideration? If the initial notification was `30px` and the new content spans to `90px` then the notification display is messed up.

Thank you for your reply! First of all, I'm really sorry for the sloppy PR. Missing height adjustment wasn't the only problem with it :-( I've taken more time to get familiar with the code base today and (hopefully) fixed it: The `setState()` statement now works as intended, plus the notification height is being re-calculated.

Since the ids are now more essential than before, I also went ahead and made the `parseNotification()` helper use (somewhat) random default ids rather than the counter value. I hope this prevents collisions in case ids from a database with sequential numbers are used.

Here's a video of my testing:

https://user-images.githubusercontent.com/3873068/112510199-80772b80-8d91-11eb-998d-eda73d11eb80.mp4

**Comment by UlbeFerranCastillo** [comment]
Hi! 
You could test this pull request and if the result is positive, mix it with master. It is quite useful that notifications with the same id are replaced, since otherwise there are alerts for duplicate Id and it is annoying to see the same message several times, especially when you have different asynchronous calls and the server returns a 403 there are as many notifications as errors . Obviously I have my way of controlling that it does not happen, but it is not a natural behavior and I think there should be a way to prevent notifications with the same ID from being duplicated.

Thanks !

**Comment by teodosii** [comment]
Merging this into master, thank you for contributing! Sorry for the extended delay.

**Pull request merged**
